// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qpV1tQTenlfcyyuixPjGOskC91GPu2Q',
    appId: '1:1047298477177:web:9313891e291dd3c64f18a8',
    messagingSenderId: '1047298477177',
    projectId: 'clezygov',
    authDomain: 'clezygov.firebaseapp.com',
    storageBucket: 'clezygov.appspot.com',
    measurementId: 'G-47H8VESVNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANxveTJDnVYEwFgivmUifmXfe6Fg2ZucE',
    appId: '1:1047298477177:android:cc8b29cf4df570984f18a8',
    messagingSenderId: '1047298477177',
    projectId: 'clezygov',
    storageBucket: 'clezygov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM06YesLGe-18RaZIqdtLBCPnEgaeQqWY',
    appId: '1:1047298477177:ios:0e18d8343b769e4a4f18a8',
    messagingSenderId: '1047298477177',
    projectId: 'clezygov',
    storageBucket: 'clezygov.appspot.com',
    iosBundleId: 'com.example.clezigov',
  );
}
